version: 2
updates:
  # Caddy Docker
  - package-ecosystem: "docker"
    directory: "/caddy"
    schedule:
      interval: "daily"

  # Pihole Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # Unifi Docker
  - package-ecosystem: "docker"
    directory: "/unifi"
    schedule:
      interval: "daily"

  # Wireguard Server Docker
  - package-ecosystem: "docker"
    directory: "/wireguard_server"
    schedule:
      interval: "daily"
