version: 2
updates:
  # Caddy Docker
  - package-ecosystem: "docker"
    directory: "/caddy"
    schedule:
      interval: "daily"

  # Pihole Docker
  - package-ecosystem: "docker"
    directory: "/pihole"
    schedule:
      interval: "daily"

  # unifi Docker
  - package-ecosystem: "docker"
    directory: "/unifi"
    schedule:
      interval: "daily"
