name: Check for updates
on:
  workflow_dispatch:
  schedule:
  # The "*" (#42, asterisk) character has special semantics in YAML, so this
  # string has to be quoted.
  - cron: '0 6 * * 6'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v35.1.2
        with:
          configurationFile: renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
